### PR TITLE
#113 Fixing contrast issues

### PR DESCRIPTION
**Pull request by TeraMike**
## Description

Green success popups ('snackbars') have been darkened slightly to increase contrast with white text on green background, found in setStfcColourTheme.

Before:  
image

After:  
image

## Motivation and Context

Success banners should be more legible.
Issue: https://github.com/UserOfficeProject/stfc-user-office-project/issues/113

## How Has This Been Tested

Conforms to WAVE tool standard, is actually same colour as the green textboxes used within that.

## Depends on

Related to: https://github.com/UserOfficeProject/user-office-frontend/pull/507

### CODE REVIEW

**Review by JEThompson97 — APPROVED** [review]
👍

**Comment by TeraMike** [comment]
> 👍
> Would you mind adding before and after screenshots?

Both now have screenshots :)

**Comment by JEThompson97** [comment]
Cheers for that @TeraMike !
With these types of PRs which make visual changes, I'm personally a big fan of screenshots 😁

**Comment by TeraMike** [comment]
> Cheers for that @TeraMike !
> With these types of PRs which make visual changes, I'm personally a big fan of screenshots 😁

It's good practise for me to keep in mind so people know what I'm talking about! 😄

**Review by simonfernandes — APPROVED** [review]

**Pull request merged**
