### PR TITLE
fix: GDPR concerns exposed over GraphQL

### PR DESCRIPTION
**Pull request by sc19ew**
<details>
<summary>Old description</summary>
## Description
Closes: UserOfficeProject/stfc-user-office-project/issues/209 

## Motivation and Context
The queries `getBasic` and `getUser` were accessible to all users and the scope of who can access these needed to be narrowed to prevent any GDPR violations. 

## How Has This Been Tested
I tested my changes by making proposals locally testing that my changes didn't break the functionality for adding a PI, a co-proposer or generating the pdf.

## Fixes
Closes: UserOfficeProject/stfc-user-office-project/issues/209 

## Changes
Changes made to:
 `UserQueries.ts` - added new query for adding a PI to proposal, added USER_OFFICER and INSTRUMENT_SCIENTIST permissions to `getBasic` and `getUser`, as well as adding `Authorized` decorator to `getProposers`.
`resolvers/types/Proposal.ts` - proposer resolver points to new query.
`resolvers/types/EventLogs.ts` - altered call to `getUser` to match changes.
`factory/pdf/proposal.ts` - get PI for PDF points to new query.

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated
</details>

## Description
Closes: UserOfficeProject/stfc-user-office-project/issues/209 

## Motivation and Context
The queries `getBasic` and `getUser` were accessible to all users and the scope of who can access these needed to be narrowed to prevent any GDPR violations. 

## How Has This Been Tested
I tested my changes by making proposals locally testing that my changes didn't break the functionality for adding a PI, a co-proposer or generating the pdf.

## Fixes
Closes: UserOfficeProject/stfc-user-office-project/issues/209 

## Changes

Changes made to:
`resolvers/types/EventLogs.ts` - altered call to `getUser` to match changes.
`UserQueries` - added USER_OFFICER and INSTRUMENT_SCIENTIST permissions to `getUser`, as well as adding `Authorized` decorator to `getProposers`. Added `haspermissions` to getBasic which calls ` canReadUser` from `UserAuthorization`.
 
`UserAuthorization` - `canReadUser` checks if the user has the correct permissions to get user details, which is if you are:
- a User Officer
- an Instrument Scientist
- a chair or secretary of an SEP panel relating to the user
- on a visit with the user
- on a proposal with the user 

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

### CODE REVIEW

**Review by TickleThePanda — CHANGES_REQUESTED** [review]
Accidentally submitted my changes requested as approved. See other comments.

**Review by TickleThePanda — APPROVED** [review]

**Review by TCMeldrum — DISMISSED** [review]

**Review by vyshnavi1605 — APPROVED** [review]

**Review by jekabs-karklins — APPROVED** [review]
I think this will work for now.

I have created also a dummy PR on the frontend to check if E2E passes
[E2E and build testing.](https://github.com/UserOfficeProject/user-office-frontend/actions/workflows/test-build.yml)

I can also see that it is a little challenging to figure out who should be able to access whoms information.  We could maybe consider delegating that task to UserAuth class. and implement canReadUserData(user, userId), where `user` is the accessor, and `userId` is the id of the assessee. Then the UserAuth would be responsible for figuring out the logic, that can be reused in several places. 

Future more if we have this logic in once centralized location it opens an opportunity for different logic per facility. because we could map the UserAuth to different implementation in the dependencyConfig.

**Review by ACLay — APPROVED** [review]
I think this looks good. 👍 for the data source comments, very helpful for telling what's going on in the queries.

**Review by jekabs-karklins — APPROVED** [review]

**Comment by ACLay** [comment]
This has had approvals from both sides for a while now. Is at waiting on anything else, or can it go in?

**Pull request merged**
