### PR TITLE
142 trigger deployment

### PR DESCRIPTION
**Pull request by vyshnavi1605**
## Description

Closes: https://github.com/UserOfficeProject/stfc-user-office-project/issues/142

- Created [Jenkins Job](https://ci.devs.facilities.rl.ac.uk/job/Dev_Deploy_ProposalBackend.LatestImage/) to trigger which triggers the kubernetes rollout for the backend. 
- Jenkins Job triggers when push to `master` or `develop` branch on the GitHub repo `user-office-backend` happens

## How Has This Been Tested

- After Jenkins job was created, manually triggered and made sure it was successful. 
- Then triggered the job remotely with a curl command on GitBash 
- Added the command to `build-push.yml` file, created a branch and pushed to the branch to ensure the Jenkins Job was successfully triggered. 

image
Image above shows GitHub actions has taken place after push was made. 

image
Build was triggered successfully on Jenkins

image
Command on job has been executed
## Fixes

Fixes: https://github.com/UserOfficeProject/stfc-user-office-project/issues/142
## Changes

- Made changes in `build-push.yml` file, added curl command to trigger Jenkins job
- Created [Jenkins job](https://ci.devs.facilities.rl.ac.uk/job/Dev_Deploy_ProposalBackend.LatestImage/)  
- Secrets added were: 
    - STFC_CI_TRIGGER_USERNAME
    - STFC_CI_TRIGGER_TOKEN
    - STFC_CI_TRIGGER_BASE_URL
    - STFC_CI_TRIGGER_URL_TOKEN

### CODE REVIEW

**Review by TCMeldrum — APPROVED** [review]
Looks good I assume there will be similar changes for the frontend and factory?

**Comment by vyshnavi1605** [comment]
> Looks good I assume there will be similar changes for the frontend and factory?

Yep, I'm working on the frontend changes now. What do you mean by changes for the factory?

**Comment by TCMeldrum** [comment]
We have https://github.com/UserOfficeProject/user-office-factory running on dev as well, we probably want to do the same thing there. I think it should be the exact same process

**Comment by vyshnavi1605** [comment]
> We have https://github.com/UserOfficeProject/user-office-factory running on dev as well, we probably want to do the same thing there. I think it should be the exact same process

Okay thank you, I'll make changes for that as well.

**Pull request merged**
