### PR TITLE
fix: Fix permission issues with isMemberOfSEP where we should send sepId instead of userId

### PR DESCRIPTION
**Pull request by martin-trajanovski**
## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

### CODE REVIEW

**Review by mr-field — COMMENTED** [review]
Is it necessary to pass `sepId` to the `UsersQuery`? It seems like every SEP member would have permission to get the full results, so maybe it would be easier to just make `sepId` optional in `isMemberOfSEP` and not pass any IDs when we define `isSEPMember`. If we do that, the datasource should check id the user is on any SEP without the need to pass a `sepId` to the query.

**Comment by martin-trajanovski** [comment]
> Is it necessary to pass `sepId` to the `UsersQuery`? It seems like every SEP member would have permission to get the full results, so maybe it would be easier to just make `sepId` optional in `isMemberOfSEP` and not pass any IDs when we define `isSEPMember`. If we do that, the datasource should check if the user is on any SEP without the need to pass a `sepId` to the query.

Thanks @mr-field I just pushed the fix as you suggest and it should work.

**Review by mr-field — COMMENTED** [review]
The change looks good, but I think something similar is also happening [here](https://github.com/UserOfficeProject/user-office-backend/blob/9bd37972e1aff11675380335592e021b7ce8c7d9/src/queries/SEPQueries.ts#L156). Unless I'm misundertanding the code, that check will also fail for the same reason (we're passing something which isn't a SEP ID). Maybe we can get the SEP ID of the proposal there and use it for the check?

**Comment by martin-trajanovski** [comment]
> The change looks good, but I think something similar is also happening [here](https://github.com/UserOfficeProject/user-office-backend/blob/9bd37972e1aff11675380335592e021b7ce8c7d9/src/queries/SEPQueries.ts#L156). Unless I'm misundertanding the code, that check will also fail for the same reason (we're passing something which isn't a SEP ID). Maybe we can get the SEP ID of the proposal there and use it for the check?

@mr-field thanks for the tips. I will definitely take a look.

**Review by jekabs-karklins — APPROVED** [review]
Looks good

**Pull request merged**
