### PR TITLE
refactor: Add user profile URL to fix inconsistency

### PR DESCRIPTION
**Pull request by voduguwa**
## Description

Add user profile URL to fix inconsistency seen in "Logged in as <email>" links.

## How Has This Been Tested

Ensured links are directing user to the correct page.

## Fixes
Part of UserOfficeProject/user-office-project-issue-tracker#212
Part of  UserOfficeProject/user-office-project-issue-tracker#274

## Depends on

 https://github.com/isisbusapps/docker-orchestration/pull/290

## Tests included/Docs Updated?

- [ ] I have added tests to cover my changes.
- [ ] All relevant doc has been updated

### CODE REVIEW

**Comment by mutambaraf** [comment]
Is it possible to make the fixes navigable so can easily click to see the issues
Part of user-office-project-issue-tracker#212
Part of user-office-project-issue-tracker#274

**Comment by voduguwa** [comment]
> Is it possible to make the fixes navigable so can easily click to see the issues Part of user-office-project-issue-tracker#212 Part of user-office-project-issue-tracker#274

Done! Sorry about that

**Review by simonfernandes — APPROVED** [review]
Don't forget to link https://github.com/isisbusapps/docker-orchestration/pull/290 in the "Depends on" section, as it provides important context 🙂

**Comment by voduguwa** [comment]
> Don't forget to link [isisbusapps/docker-orchestration#290](https://github.com/isisbusapps/docker-orchestration/pull/290) in the "Depends on" section, as it provides important context 🙂

Thank you!

**Pull request merged**
